name:  Publish to npmjs.com
on:
  push:
    tags:
      - "v*.*.*"
env:
    NPM_TOKEN: ${{secrets.GITLAB_NPM_TOKEN}}
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup node
      uses: actions/setup-node@v2
      with:
          node-version: 18.x
          cache: 'npm'
    - name: Publish
      run: ./publish.sh ${GITHUB_REF#refs/*/}
